require: rubocop-rails
inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Style/Documentation:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
