require:
  - rubocop-rails
  - rubocop-rspec

inherit_from: ./lib/rubocop/blacklist.yml

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable

Layout/LineLength:
  Max: 110
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude:
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Lint/MissingSuper:
  Enabled: false

# rubocop-rspec gem excludes
RSpec/NamedSubject:
   Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleMemoizedHelpers:
 Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/api_wrappers/**/*.rb'

RSpec/FilePath:
  Exclude:
    - 'spec/models/**/*.rb'

RSpec/AnyInstance:
   Enabled: false

RSpec/MessageSpies:
   Enabled: false

RSpec/InstanceVariable:
   Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
