FROM ruby:2.6.5-alpine3.11

RUN apk add --no-cache --update build-base \
  linux-headers \
  tzdata \
  nodejs \
  tzdata \
  openssh \
  libxml2-dev \
  libxslt-dev \
  yarn \
  curl-dev \
  sqlite-dev \
  git \
  && PACKAGES="ca-certificates procps curl pcre libstdc++ libexecinfo" \
  && BUILD_PACKAGES="pcre-dev libexecinfo-dev" \
  && apk add --update $PACKAGES $BUILD_PACKAGES \
  && rm -rf /var/cache/apk/*

RUN apt-get update && apt-get install -y unzip && \
    CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE` && \
    wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/ && \
    unzip ~/chromedriver_linux64.zip -d ~/ && \
    rm ~/chromedriver_linux64.zip && \
    chown root:root ~/chromedriver && \
    chmod 755 ~/chromedriver && \
    mv ~/chromedriver /usr/bin/chromedriver && \
    sh -c 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -' && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' && \
    apt-get update && apt-get install -y google-chrome-stable

# Install bundle of gems
RUN mkdir -p /home/app
WORKDIR /home/app
COPY Gemfile Gemfile.lock package.json /home/app/
RUN gem install bundler -v 2.0.2 \
 && bundle config force_ruby_platform true \
 && bundle install \
 && yarn install --frozen-lockfile --non-interactive

# Install node packages and precompile assets
COPY . /home/app

CMD ["rspec"]
